theme: jekyll-theme-primer
title: LendingClub
description: Investment strategy for LendingClub
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
